### ISSUE TITLE
Kommende matches?

### ISSUE THREAD

**Issue by kris914g** [syre/csgolounge_scraper#1]
Hej vil det være muligt at kunne få scrapped kommende matches?

**Comment by syre** [comment]
Ja, kommende som dem som allerede er i gang eller er i fremtiden?

**Comment by kris914g** [comment]
sry mener fremtidige matches ;)

**Comment by syre** [comment]
jeg har tilføjet en completed og status_text attribut nu

**Comment by kris914g** [comment]
tusinde tak!

**Comment by syre** [comment]
ingen årsag!
